### ISSUE TITLE
Can't create database

### ISSUE THREAD

**Issue by swedax94** [ChimpGamer/NetworkManager#101]
**Paper 1.19.2*

**Describe the bug**
Plugin does not generate a database neither mysql nor mariadb

**Log**
`
[10:18:47 INFO]: [NetworkManager] Enabling NetworkManager v2.12.8
[10:18:48 INFO]: [nl.chimpgamer.networkmanager.lib.hikari.HikariDataSource] networkmanager-pool - Starting...
[10:18:48 INFO]: [nl.chimpgamer.networkmanager.lib.hikari.HikariDataSource] networkmanager-pool - Start completed.
[10:18:49 ERROR]: Error occurred while enabling NetworkManager v2.12.8 (Is it up to date?)
java.sql.SQLSyntaxErrorException: Table 'zap682719-1.nm_servers' doesn't exist
at nl.chimpgamer.networkmanager.lib.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120) ~[NetworkManager-Spigot-v2.12.8.jar:?]
at nl.chimpgamer.networkmanager.lib.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122) ~[NetworkManager-Spigot-v2.12.8.jar:?]
at nl.chimpgamer.networkmanager.lib.mysql.cj.jdbc.ServerPreparedStatement.serverExecute(ServerPreparedStatement.java:555) ~[NetworkManager-Spigot-v2.12.8.jar:?]
at nl.chimpgamer.networkmanager.lib.mysql.cj.jdbc.ServerPreparedStatement.executeInternal(ServerPreparedStatement.java:339) ~[NetworkManager-Spigot-v2.12.8.jar:?]
at nl.chimpgamer.networkmanager.lib.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1061) ~[NetworkManager-Spigot-v2.12.8.jar:?]
at nl.chimpgamer.networkmanager.lib.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1009) ~[NetworkManager-Spigot-v2.12.8.jar:?]
at nl.chimpgamer.networkmanager.lib.mysql.cj.jdbc.ClientPreparedStatement.executeLargeUpdate(ClientPreparedStatement.java:1320) ~[NetworkManager-Spigot-v2.12.8.jar:?]
at nl.chimpgamer.networkmanager.lib.mysql.cj.jdbc.ClientPreparedStatement.executeUpdate(ClientPreparedStatement.java:994) ~[NetworkManager-Spigot-v2.12.8.jar:?]
at nl.chimpgamer.networkmanager.lib.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61) ~[NetworkManager-Spigot-v2.12.8.jar:?]
at nl.chimpgamer.networkmanager.lib.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java) ~[NetworkManager-Spigot-v2.12.8.jar:?]
at nl.chimpgamer.networkmanager.common.storage.sql.SQLStorageManager.updateDatabase(SQLStorageManager.kt:92) ~[NetworkManager-Spigot-v2.12.8.jar:?]
at `

**Version Information:**
 - NetworkManager: NetworkManager-Spigot-v2.12.8.jar
 - Spigot/Paper: 1.19.2

**Additional context**
Add any other context about the problem here. Remove this section if not used.

**Comment by ChimpGamer** [comment]
Use MySQL 8 or newer. If you use MariaDB then you need version 10.3 or newer. Also make sure to start the plugin first on BungeeCord or Velocity.
