### ISSUE TITLE
error /gtempban

### ISSUE THREAD

**Issue by Acixsi** [ChimpGamer/NetworkManager#35]
Error wanneer je /gtempban <naam> <duration> doet, en geen reason opgeeft.:

[19:11:38] [Netty Worker IO Thread #6/WARN]: Error in dispatching command
java.lang.ArrayIndexOutOfBoundsException: 1
	at nl.chimpgamer.networkmanager.bungeecord.commands.general.PunishmentCommand.onExecute(PunishmentCommand.java:220) ~[?:?]
	at nl.chimpgamer.networkmanager.api.commands.NMBungeeCommand.execute(NMBungeeCommand.java:56) ~[?:?]
	at net.md_5.bungee.api.plugin.PluginManager.dispatchCommand(PluginManager.java:192) ~[waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:b02f64c:327]
	at net.md_5.bungee.api.plugin.PluginManager.dispatchCommand(PluginManager.java:142) ~[waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:b02f64c:327]
	at net.md_5.bungee.connection.UpstreamBridge.handle(UpstreamBridge.java:152) ~[waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:b02f64c:327]
	at net.md_5.bungee.protocol.packet.Chat.handle(Chat.java:60) ~[waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:b02f64c:327]
	at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:105) ~[waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:b02f64c:327]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:b02f64c:327]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:b02f64c:327]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:b02f64c:327]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) ~[waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:b02f64c:327]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:b02f64c:327]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:b02f64c:327]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:b02f64c:327]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) ~[waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:b02f64c:327]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:b02f64c:327]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:b02f64c:327]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:b02f64c:327]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:321) ~[waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:b02f64c:327]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:295) ~[waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:b02f64c:327]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:b02f64c:327]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:b02f64c:327]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:b02f64c:327]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) ~[waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:b02f64c:327]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:b02f64c:327]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:b02f64c:327]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:b02f64c:327]
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:b02f64c:327]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:b02f64c:327]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:b02f64c:327]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:b02f64c:327]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:b02f64c:327]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:b02f64c:327]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:b02f64c:327]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:b02f64c:327]
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:792) ~[waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:b02f64c:327]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:475) ~[waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:b02f64c:327]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378) ~[waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:b02f64c:327]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:b02f64c:327]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:b02f64c:327]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
[19:11:53] [Netty Worker IO Thread #6/INFO]: [Chopstick09] disconnected with: You have been temp-banned from the network
 Banned by: Acixsi
Reason: No reason provided
Remaining time: 10 Seconds

**Comment by ChimpGamer** [comment]
En welke versie van NetworkManager is dit?

**Comment by Acixsi** [comment]
De meest recente build uit Discord

**Comment by ChimpGamer** [comment]
Ik heb geen problemen met het command. Weet je zeker dat je de laatste build gebruikt?

**Comment by Acixsi** [comment]
/gtempban JustBerry 10s

In bovenstaand geval probeer ik te bannen zonder reason, en ipv dat ik een return krijg dat ik een reason moet invullen krijg ik de error.

**Comment by ChimpGamer** [comment]
Werkt het commando wel gewoon in console?

**Comment by Acixsi** [comment]
Nou t is dus meer een bug, ik kan het commando wel uitvoeren als ik een reden invul, t is alleen meer dat er waarschijnlijk in de plugin niet goed op argslength gecheckt wordt dat als je ingame het commando uitvoert dat je dan een error ipv een too few arguments krijgt

**Comment by ChimpGamer** [comment]
Ik krijg dezelfde error maar alleen als ik geen tijd opgeef. Deze error ga ik oplossen.

**Comment by ChimpGamer** [comment]
Fixed in latest version of NetworkManager available on SpigotMC.
